apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment  
spec:
  replicas: 1
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container   
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: portal-noticias-configmap
  selector:
    matchLabels:
      app: sistema-noticias       
            
